@URL = http://api.core/
@TOKEN = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MzIzNTgzMDIsImV4cCI6MTUzMjQ0NDcwMiwiZGF0YSI6eyJJRCI6IjEiLCJ1c2VyIjoiYWRtaW4iLCJlbWFpbCI6IndlYm1hc3RlckBnbWFpbC5jb20iLCJwYXNzIjoiJDEkIURFUComOz0kNUljT3dWdmlVd1wvTDhZVHA5b3R0RzAiLCJuYW1lIjoiZGF2aWQiLCJsYXN0Ijoic2FsaW5hcyIsImJpcnRoIjoiMTk4MC0wNC0xMyIsImFjY2VzcyI6IjUiLCJhY3RpdmUiOiIxIn19.os8KiBOVhEUkX50q4eCtgXzzi8x_rlaehzvQ7z-mAv0
@FORMAT = ?format=json

### Main
GET {{URL}}/{{FORMAT}}

### About Page
GET {{URL}}/about

### Login user
POST {{URL}}login{{FORMAT}}

{
    "user":"admin",
    "pass":"d0708aca"
}

### Check if user exist
POST {{URL}}/user/check{{FORMAT}}

{
    "user":"admin"
}

### Crear Usuario
POST {{URL}}/user/edit{{FORMAT}}
Authorization: {{TOKEN}}

{
   "user":"saotand",
   "pass":"tvxq1aca",
   "name":"David",
   "last":"Salinas",
   "email":"saotand@gmail.com",
   "birth":"1983-04-13",
   "access":"5",
   "active":"0"
}

### Editar Usuario
POST {{URL}}/user/edit{{FORMAT}}
Authorization: {{TOKEN}}

{
    "ID":"2",
    "from":"1",
    "data":{
        "name":"sa"
    }
}

###
POST {{URL}}user/del{{FORMAT}}
Authorization: {{TOKEN}}

{
    "ID":"2",
    "from":"1"
}