@URL = http://api.core/
@TOKEN = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MzQ0NzI3NTQsImV4cCI6MTUzNDU1OTE1NCwiZGF0YSI6eyJJRCI6IjEiLCJ1c2VyIjoiYWRtaW4iLCJlbWFpbCI6IndlYm1hc3RlckB3ZWJtaW5hcHBzLmNvbSIsInBhc3MiOiIkMSQhREVQKiY7PSRINk54dkJyZnQwbVd3QkxDU3RPMjYwIiwibmFtZSI6IkFkbWluaXN0cmF0b3IiLCJsYXN0IjoiU3lzdGVtIiwiYmlydGgiOiIxOTgzLTA0LTEzIiwiYWNjZXNzIjoiNSIsImFjdGl2ZSI6IjEifX0.4xcAOiUnodor9k_GyFiOSN3H2TX9UnhRHTWRDqXxFGo
@FORMAT = ?format=json

### Main
GET {{URL}}/{{FORMAT}}

### About Page
GET {{URL}}/about

### User data ID
GET {{URL}}user/1
Authorization: {{TOKEN}}

### User List
GET {{URL}}/user
Authorization: {{TOKEN}}

### Login user
POST http://api.core/login?format=json

{
    "user":"admin",
    "pass":"tvxq1aca"
}

### New User
POST {{URL}}user/new{{FORMAT}}

{
    "user":"saotand",
    "email":"saotand@gmail.com",
    "pass":"d0708aca",
    "name":"David",
    "last":"Salinas",
    "birth":"1983-04-13",
    "access":"5",
    "active":"1"
}

### Check if user exist
POST {{URL}}/user/check{{FORMAT}}

{
    "user":"admin"
}

### Crear Usuario
POST {{URL}}/user/edit{{FORMAT}}
Authorization: {{TOKEN}}

{
    "from":"2",
    "ID":"2",
    "data":{
        "user":"saotand",
        "pass":"d0708aca",
        "name":"David",
        "last":"Salinas",
        "email":"saotand@gmail.com",
        "birth":"1983-04-13",
        "access":"5",
        "active":"1"
    }
}

### Editar Usuario
POST {{URL}}/user/edit{{FORMAT}}
Authorization: {{TOKEN}}

{
    "ID":"2",
    "from":"1",
    "data":{
        "name":"sa"
    }
}

###
POST {{URL}}user/del{{FORMAT}}
Authorization: {{TOKEN}}

{
    "ID":"2",
    "from":"1"
}


###
GET {{URL}}task{{FORMAT}}

###
GET {{URL}}task/1{{FORMAT}}

